export type BadgeTone = 'brand' | 'positive' | 'warning' | 'critical' | 'informative' | 'neutral';

export type IconName =
  | 'arrow-left'
  | 'bell'
  | 'check'
  | 'chevron-right'
  | 'clock'
  | 'close'
  | 'adjust'
  | 'balance'
  | 'diamond'
  | 'dialpad'
  | 'eco'
  | 'extension'
  | 'fire'
  | 'flask'
  | 'groups'
  | 'hand'
  | 'lock'
  | 'paw'
  | 'play'
  | 'profile'
  | 'rank'
  | 'report'
  | 'rotate'
  | 'settings'
  | 'share'
  | 'timeline'
  | 'trend-up'
  | 'trophy';
