import type { LucideIcon } from 'lucide-react-native';
import {
  ArrowLeft,
  ArrowRight,
  AudioLines,
  Award,
  BadgeCheck,
  Bell,
  Building2,
  Bus,
  Car,
  Captions,
  ChartNoAxesColumnIncreasing,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleCheck,
  CircleDot,
  CircleHelp,
  CircleStop,
  ClipboardPaste,
  Clock,
  CloudUpload,
  Delete,
  Droplet,
  Eye,
  Fence,
  FileText,
  Flame,
  FlaskConical,
  FlipHorizontal2,
  Flower,
  Flower2,
  Footprints,
  Gamepad2,
  Gem,
  Grid3x3,
  Hand,
  HandFist,
  Info,
  Leaf,
  Lightbulb,
  Lock,
  LogOut,
  Map,
  Mic,
  PawPrint,
  Pencil,
  Pentagon,
  Play,
  Plus,
  Puzzle,
  Rat,
  RotateCcw,
  RotateCw,
  Scale,
  Scissors,
  Settings,
  Share,
  Smile,
  Sparkles,
  Square,
  Target,
  ThumbsUp,
  Timeline,
  Trees,
  TrendingUp,
  Triangle,
  Trophy,
  User,
  UserRoundPlus,
  UsersRound,
  Utensils,
  Video,
  Volume2,
  Wheat,
  X,
  Zap,
} from 'lucide-react-native';

import { useDesignSystemTheme } from '../../design-system/provider';
import { resolveColor } from '../../design-system/components/style-props';
import type { ColorToken } from '../../design-system/components/style-props';
import type { IconName } from '../../shared/types';

export type { IconName } from '../../shared/types';

export type IconProps = {
  name: IconName;
  color?: ColorToken;
  size?: 'small' | 'medium' | 'large';
};

const lucideIconByName: Record<IconName, LucideIcon> = {
  ArrowLeft,
  ArrowRight,
  AudioLines,
  Award,
  BadgeCheck,
  Bell,
  Building2,
  Bus,
  Car,
  Captions,
  ChartNoAxesColumnIncreasing,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleCheck,
  CircleDot,
  CircleHelp,
  CircleStop,
  ClipboardPaste,
  Clock,
  CloudUpload,
  Delete,
  Droplet,
  Eye,
  Fence,
  FileText,
  Flame,
  FlaskConical,
  FlipHorizontal2,
  Flower,
  Flower2,
  Footprints,
  Gamepad2,
  Gem,
  Grid3x3,
  Hand,
  HandFist,
  Info,
  Leaf,
  Lightbulb,
  Lock,
  LogOut,
  Map,
  Mic,
  PawPrint,
  Pencil,
  Pentagon,
  Play,
  Plus,
  Puzzle,
  Rat,
  RotateCcw,
  RotateCw,
  Scale,
  Scissors,
  Settings,
  Share,
  Smile,
  Sparkles,
  Square,
  Target,
  ThumbsUp,
  Timeline,
  Trees,
  TrendingUp,
  Triangle,
  Trophy,
  User,
  UserRoundPlus,
  UsersRound,
  Utensils,
  Video,
  Volume2,
  Wheat,
  X,
  Zap,
};

const iconSizeToken = {
  small: 'x5',
  medium: 'x6',
  large: 'x8',
} as const;

export function Icon({ name, color = 'fg.neutralMuted', size = 'medium' }: IconProps) {
  const { theme } = useDesignSystemTheme();
  const resolvedColor = resolveColor(theme, color) ?? color;
  const LucideIcon = lucideIconByName[name];

  return (
    <LucideIcon
      color={resolvedColor}
      size={theme.dimension.x[iconSizeToken[size]]}
      strokeWidth={2}
      absoluteStrokeWidth
    />
  );
}
